name: tests
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  permission_handler: ^9.1.0
  path_provider: ^2.0.9
  path: ^1.8.0
  http: ^0.13.4
  logger: ^1.1.0
  url_launcher: ^6.0.17
  cached_network_image: ^3.2.0
  flutter_staggered_grid_view: ^0.6.1
  retrofit: ^3.0.1+1
  image_picker: ^0.8.4+10
  dio: ^4.0.4
  provider: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter


  flutter_lints: ^1.0.0
  retrofit_generator: ^4.0.1
  build_runner: ^2.1.7


flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/fonts/



  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
